name: Deploy KoLmafia script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packages/wishlist-mafia"
    name: Build and Push
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.23"

      - name: Install dependencies
        run: bun install

      - name: Build script
        run: bun run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: packages/wishlist-mafia/dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          SKIP_EMPTY_COMMITS: true
