// Pure geometry helpers for ListEntry layout.
//
// Mirrors the CSS clamp formulas generated by tailwind-clamp for the entry's
// layout primitives. Each function takes the **layout viewport width** in px
// (i.e. `document.documentElement.clientWidth`, which excludes scrollbar) and
// returns a closed-form result; downstream code (e.g. pretext height
// computation) can rely on these without DOM measurement.
//
// Note on viewport parameter: CSS `vw` resolves against the layout viewport,
// not `window.innerWidth`. When a vertical scrollbar is present the two differ
// by ~15px, and feeding `innerWidth` into clamp formulas gives wrong values
// near max-padding regions. Always pass `documentElement.clientWidth`.
//
// Source clamp formulas read from packages/wishlist-web/src/components/entry/*
// and confirmed against generated CSS via DevTools.
//
// TODO(pocket-wishlist-j4f): un-hardcode the CSS↔TS mappings here. Every clamp
// formula below mirrors a tailwind-clamp utility by hand; if the CSS changes,
// virtualizer heights silently drift. Options: codegen from the source JSX
// classes, dev-mode self-check against DOM measurements at probe time, or
// migrating clamp parameters to shared CSS custom properties read at runtime.

const clampPx = (
  min: number,
  max: number,
  interceptPx: number,
  slopeVwPct: number,
  vp: number,
): number =>
  Math.min(max, Math.max(min, interceptPx + (slopeVwPct / 100) * vp));

// App.tsx:18 — clamp-[px,4,10,md,lg] → clamp(1rem, -3.5rem + 9.375vw, 2.5rem)
export const pagePaddingX = (vp: number): number =>
  clampPx(16, 40, -56, 9.375, vp);

// App.tsx:18 — lg:max-w-5xl (1024px) caps the inner container once vp ≥ lg.
export const pageContentWidth = (vp: number): number => {
  const widthBeforePadding = vp >= 1024 ? Math.min(vp, 1024) : vp;
  return widthBeforePadding - 2 * pagePaddingX(vp);
};

// ListEntry.tsx:127 — min-w-[290px] keeps the row at least 290px wide.
export const rowOuterWidth = (vp: number): number =>
  Math.max(290, pageContentWidth(vp));

// ListEntry.tsx:129 — clamp-[px,5,6,xs,sm] → clamp(1.25rem, 1rem + 1.25vw, 1.5rem)
export const rowPaddingX = (vp: number): number =>
  clampPx(20, 24, 16, 1.25, vp);

export const rowContentWidth = (vp: number): number =>
  rowOuterWidth(vp) - 2 * rowPaddingX(vp);

// EntryInfoSection.tsx:38 — w-0 basis-full at xs/sm/md, lg:basis-auto.
// At xs/sm/md it occupies its own flex line at full row content width.
// At lg+ it shares the row with siblings; not yet modeled (TODO Phase 1b).
export const sectionContentWidth = (vp: number): number => rowContentWidth(vp);

// EntryInfoSection.tsx:54 — clamp-[size,6,7,sm,md] → clamp(1.5rem, 0.25rem + 3.125vw, 1.75rem)
export const imageContentSize = (vp: number): number =>
  clampPx(24, 28, 4, 3.125, vp);

// `m-2` on the ThemedImg adds 8px on each side; the wrapping <a> has min-w-fit
// so the image's box width is content + 16px regardless of available space.
export const imageBoxWidth = (vp: number): number => imageContentSize(vp) + 16;

// EntryItem wrapping the year Badge: Badge has w-14 (56px) which dominates the
// label width across all breakpoints we render at.
export const YEAR_COLUMN_WIDTH = 56;

// EntrySection.tsx:8 + EntryInfoSection.tsx:38 — gap-5 = 20px between section children.
export const SECTION_GAP = 20;

// EntryInfoSection.tsx:58 — clamp-[w,42,56,md,lg] → clamp(10.5rem, 0rem + 21.875vw, 14rem)
// Below md the clamp pins at its 168px min.
export const nameColumnNominalWidth = (vp: number): number =>
  clampPx(168, 224, 0, 21.875, vp);

// Actual rendered name-column width: at narrow viewports flex-shrink narrows
// the EntryItem so the nominal 168px becomes whatever the row leaves over.
export const nameColumnWidth = (vp: number): number => {
  const nominal = nameColumnNominalWidth(vp);
  const available =
    sectionContentWidth(vp) -
    imageBoxWidth(vp) -
    YEAR_COLUMN_WIDTH -
    2 * SECTION_GAP;
  return Math.min(nominal, available);
};

// EntryInfoSection.tsx:60 — clamp-[text,sm,base,xs,sm]
//   font-size:   clamp(0.875rem, 0.75rem + 0.625vw, 1rem)
//   line-height: clamp(1.25rem, 1rem + 1.25vw, 1.5rem)
export const nameFontSizePx = (vp: number): number =>
  clampPx(14, 16, 12, 0.625, vp);

export const nameLineHeightPx = (vp: number): number =>
  clampPx(20, 24, 16, 1.25, vp);
